version: "3"
services:
    redis:
        image: redis:latest
        restart: unless-stopped

    app:
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            PYTHONUNBUFFERED: 1
            USERNAME: ${STEAM_USERNAME}
            PASSWORD: ${STEAM_PASSWORD}
            SHARED_SECRET: ${STEAM_SHARED_SECRET}
            REDIS_URI: ${REDIS_URI}
        depends_on:
            - redis
        restart: unless-stopped
